# Generated by Django 2.2 on 2021-02-19 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Project', max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('AI_algo', models.TextField()),
                ('cust_seq', models.TextField()),
                ('cust_dur', models.TextField()),
                ('cust_speed', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploadedFiles/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Project')),
            ],
        ),
    ]
