# Generated by Django 2.2 on 2021-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210219_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.URLField(default='nothing'),
            preserve_default=False,
        ),
    ]
