# Generated by Django 2.2 on 2021-02-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.FileField(upload_to='projectFiles/'),
        ),
    ]
